#!/bin/bash

#  _
# | |
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           | |
#           |_|

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

# remove all rules first
bspc rule -r *:*

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

## Configurations -------------------------------#
bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config top_padding 30
bspc config bottom_padding 30

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer false

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BLACK"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

#Floating applications
bspc rule -a termite-float state=floating follow=on focus=on
bspc rule -a alacritty-float state=floating follow=on focus=on
bspc rule -a Gpick state=floating follow=on focus=on
bspc rule -a feh state=floating follow=on focus=on
bspc rule -a KeePassXC state=floating center=true
bspc rule -a Nitrogen state=floating center=true
bspc rule -a Gcolor3 state=floating follow=on focus=on
bspc rule -a mpv state=floating follow=on focus=on
bspc rule -a smplayer state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on

#open applications on specific workspaces
#bspc rule -a Chromium -o desktop=^3
